version: '3'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: 'phpserver'
    environment:
      - ALLOW_OVERRIDE=true
    links:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - "80:80"
#      - "443:443"    # HTTPS PORT
  db:
    image: mariadb
    container_name: 'phpserver-database'
    restart: always
    volumes:
      - ./database/data/mysql:/var/lib/mysql
      - ./database/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 'devpass'
    ports:
      - "8889:3606"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpserver-phpmyadmin'
    depends_on:
      - db
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_USER: dev
      PMA_PASSWORD: 'devpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: dev
      MYSQL_PASSWORD: 'devpass'
    ports:
      - "8900:80"
